### ISSUE TITLE
OverflowError: signed integer is greater than maximum

### ISSUE THREAD

**Issue by navado** [JosPolfliet/pandas-profiling#69] opened 2017-11-13 00:29 UTC
Code:
```
import pandas as pd
import numpy as np
import pandas_profiling

df = pd.read_csv('/tmp/a.t',sep='\t')
df.replace(to_replace=["\\N"," "],value=np.nan,inplace=True)
pfr = pandas_profiling.ProfileReport(df.head())
pfr.to_file("/tmp/example.html")
```

Stack trace:
```
  File "<ipython-input-22-5d56f8a2a91a>", line 9, in <module>
    pfr = pandas_profiling.ProfileReport(df)

  File "/home/user/.local/lib/python3.5/site-packages/pandas_profiling/__init__.py", line 17, in __init__
    description_set = describe(df, **kwargs)

  File "/home/user/.local/lib/python3.5/site-packages/pandas_profiling/base.py", line 284, in describe
    ldesc = {col: s for col, s in pool.map(local_multiprocess_func, df.iteritems())}

  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()

  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value

OverflowError: signed integer is greater than maximum

/home/user/.local/lib/python3.5/site-packages/pandas_profiling/base.py:223: RuntimeWarning: divide by zero encountered in long_scalars
  'p_unique': distinct_count / count}
```

Example of the data (tab separated):
```
ts	b	c	d	e	f	g	h	i	j	k
1234576601963	63992632	320	97123492385	4	325	value234	520938	HASH	\N	const
1234572654839	28444632	319	96761692385	4	325	value1	520938	HASH	\N	const
1234573590399	58412632	320	96830092385	4	325	value1	520938	HASH	\N	const
1234573550737	63312632	320	96822892385	4	325	value1	520938	HASH	\N	const
1234575246094	74492632	320	96903892385	4	325	value234	520938	HASH	\N	const
1234576285832	64342632	320	97067692385	4	325	value234	520938	HASH	\N	const
1234567951818	35632	319	96759642785	4	310	value917	520938	HASH	\N	const
1234574017225	90822632	320	96872692385	4	325	value1	520938	HASH	\N	const
1234575810946	70392632	320	96992692385	4	325	value234	520938	HASH	\N	const
```

**Comment by romainx** [comment] 2017-11-13 20:59
I was not able to reproduce the problem with the example provided.

```python
import pandas as pd
import numpy as np
import io
import pandas_profiling

zz = """ts	b	c	d	e	f	g	h	i	j	k
1234576601963	63992632	320	97123492385	4	325	value234	520938	HASH	\\N	const
1234572654839	28444632	319	96761692385	4	325	value1	520938	HASH	\\N	const
1234573590399	58412632	320	96830092385	4	325	value1	520938	HASH	\\N	const
1234573550737	63312632	320	96822892385	4	325	value1	520938	HASH	\\N	const
1234575246094	74492632	320	96903892385	4	325	value234	520938	HASH	\\N	const
1234576285832	64342632	320	97067692385	4	325	value234	520938	HASH	\\N	const
1234567951818	35632	319	96759642785	4	310	value917	520938	HASH	\\N	const
1234574017225	90822632	320	96872692385	4	325	value1	520938	HASH	\\N	const
1234575810946	70392632	320	96992692385	4	325	value234	520938	HASH	\\N	const
"""

df = pd.read_table(io.StringIO(zz), delim_whitespace=True)
df.replace(to_replace=["\\N"," "],value=np.nan,inplace=True)
pandas_profiling.describe(df)

# {'freq': {'b': 70392632    1
#  58412632    1
# 74492632    1
# [...]
```
Please could you provide an example permitting to reproduce the error?

Many thanks.

Note: The `RuntimeWarning: divide by zero encountered in long_scalars 'p_unique': distinct_count / count}` has been fixed in #56.

**Comment by navado** [comment] 2017-11-14 08:27
Well, it might be version related.
How can I check pandas_profiling version?

**Comment by romainx** [comment] 2017-11-14 09:46
You can check it with `pip list | grep pandas-profiling`

**Comment by navado** [comment] 2017-11-14 16:11
`pandas-profiling (1.4.0)` but I installed from the master branch on top. Is there a variable to check in runtime?

**Comment by romainx** [comment] 2017-11-14 19:42
No I don't think so (I will check more closely). However, if your version does not work with the flag `check_correlation` you are running the 1.4 version and not the latest from the master branch.

**Comment by romainx** [comment] 2018-01-02 21:16
Hello,

Can I close this issue? I don't know how to go further.

Thanks

**Comment by navado** [comment] 2018-01-03 16:50
Seems so, thank you.

**Comment by romainx** [comment] 2018-01-04 06:07
Ok thanks for your reply.

**Closed by romainx** 2018-01-04 06:07 UTC
Labels: wontfix
