### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by bacalfa** [JosPolfliet/pandas-profiling#61] opened 2017-10-06 20:34 UTC
This error comes up as follows (Python 3.6):

    File "C:\Users\me\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas_profiling\__init__.py", line 17, in __init__
    description_set = describe(df, **kwargs)
    File "C:\Users\me\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas_profiling\base.py", line 294, in describe
    if correlation_overrides and x in correlation_overrides:
    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

I believe the problem is in line [294](https://github.com/JosPolfliet/pandas-profiling/blob/39f63ce420d81ef0ca6ed9ce7c1f4bb66a710925/pandas_profiling/base.py#L296) of base.py:

     if correlation_overrides and x in correlation_overrides:

I think it should be changed to the following:

     if correlation_overrides is not None and x in correlation_overrides:

Same goes for line [307](https://github.com/JosPolfliet/pandas-profiling/blob/39f63ce420d81ef0ca6ed9ce7c1f4bb66a710925/pandas_profiling/base.py#L307):

     if correlation_overrides is not None and name1 in correlation_overrides:

**Comment by romainx** [comment] 2017-11-04 19:28
Hello,

I've reproduced the problem, I think it's related to the `correlation_overrides` type. If it's a `list` it works fine.

```python
df = pd.DataFrame({'A': [1,2,3], 'B': [1,2,3], 'C': [1,2,3]})
correlation_overrides = ['A', 'B']

corr = df.corr()
for x, corr_x in corr.iterrows():
    if correlation_overrides and x in correlation_overrides:
        print('{} -> skipped'.format(x))
# A -> skipped
# B -> skipped
```

However, the problem occurs when we run the same code with an `array`.
```python
correlation_overrides = np.array(['A', 'B'])
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Please could you confirm that it works if you use a `list` instead of an `array`?
You can convert it to a `list` by doing `correlation_overrides.tolist()`.

If it's the case, we may let it as is since I don't know if this parameter is intended to be an `array`.

Many thanks

**Comment by bacalfa** [comment] 2017-11-04 19:53
Thanks, that works. That was happening because I was setting `correlation_overrides` to the `.columns.values` attribute of a pandas DataFrame. If I convert the array to a list, the original code works.

**Comment by romainx** [comment] 2017-11-04 20:08
Thanks for this quick answer!
So I close the issue without fixing it.

**Closed by romainx** 2017-11-04 20:08 UTC
Labels: wontfix

**Comment by Prithvicena** [comment] 2018-05-02 19:39
if result[0][0] == 1:
       prediction = 'dog'
else:
       prediction = 'cat'

error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
help plz

**Comment by datianshi21** [comment] 2018-11-26 08:12
Same problem whereas the type error is reported in tensorflow.

**Comment by Naj-code** [comment] 2019-10-31 04:04
Dear all please help me. I am struggling with the same problem for more then 4 days. and couldn't find any solution.
here is my code:
def build_rand_feat():
    X = []
    Y = []
    #m = df[df.columns[1]]
    _min , _max = float('inf'), -float('inf')
    for _ in tqdm(range(n_samples)):
        rand_class =np.random.choice(class_dist.index , p=prob_dist)
        file = np.random.choice(df[df.label==rand_class].index)
        rate , wav = wavfile.read('speech_commands/' + file)
        label = df.at[file , 'label']
        rand_index = np.random.randint(0 , wav.shape[0]-config.step)
        sample = wav[rand_index:rand_index+config.step]
        x_sample = mfcc(sample , rate , numcep = config.nfeat , nfilt =config.nfilt , nfft =config.nfft).T
        _min = min(np.amin(x_sample), _min)
        _max = max(np.amax(x_sample), _max)
        X.append(x_sample if config.mode == 'conv' else x_samples.T)
        Y.append(classes.index(label))
          
    X,Y = np.array(X), np.array(Y)
    X = (X - _min)/(_max - _min)
    if config.mode == 'conv':
        X = X.reshape(X.shape[0], X.shape[1] , X.shape[2],1)
    elif config.mode =='time':
        X = X.reshape(X.shape[0], X.shape[1] , X.shape[2])
        Y = to_categorical(Y , num_classes= 3)
    return X,Y


and the error occurs for  this line of code    Y.append(classes.index(label))
